apiVersion: v1
kind: Pod
metadata:
  name: pod02
spec:
  containers:
    - name: nginx
      image: nginx

    - name: mongo
      image: mongo
---
## Annotations & labels
apiVersion: v1
kind: Pod
metadata:
  name: pod03
  annotations:
    imageregistry: "https://hub.docker.com/"
  labels:
    name: annotations-demo
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
## Namespace & Image pull policy
apiVersion: v1
kind: Pod
metadata:
  name: pod04
  namespace: kube-system
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
---
### Resources
apiVersion: v1
kind: Pod
metadata:
  name: pod05
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
---
##Termination message path & policy
apiVersion: v1
kind: Pod
metadata:
  name: termination-demo
spec:
  containers:
    - name: mongo
      image: mongo
      command: ["/bin/sh"]
      args: ["-c", "sleep 10 && echo Sleep expired > /dev/termination-log"]
---
## Volume mount
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
    - name: volume
      image: mongo
      command: [ "/bin/sh" ]
      args: [ "-c", "while true ; do date ; sleep 2; done" ]
      volumeMounts:
        - mountPath: /data
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        path: /data
        type: Directory

