apiVersion: v1
kind: Pod
metadata:
  name: pod02
spec:
  containers:
    - name: nginx
      image: nginx

    - name: mongo
      image: mongo
---
## Annotations & labels
apiVersion: v1
kind: Pod
metadata:
  name: pod03
  annotations:
    imageregistry: "https://hub.docker.com/"
  labels:
    name: annotations-demo
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
## Namespace & Image pull policy
apiVersion: v1
kind: Pod
metadata:
  name: pod04
  namespace: kube-system
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always