apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replica: 3
  selector:
    matchLabels:
      tier: frontend
      type: rs
  template:
    metadata:
      labels:
        tier: frontend
        type: rs
    spec:
      containers:
        - name: nginx
          image: nginx